### ISSUE TITLE
画像比較テストの画像の取得に失敗している

### ISSUE THREAD

**Issue by sasaplus1** [openameba/a11y-guidelines#182]
<img width="1341" alt="スクリーンショット 2021-03-24 14 02 43" src="https://user-images.githubusercontent.com/309466/112258335-af19d700-8ca9-11eb-815b-47b9a898bd24.png">

`Cannot GET xxx` という画像を取得していて画像比較の意味がないので、`scrape.js`で画像取得に失敗した場合に`exitCode`を0以外で返すようにして発見できるようにしたり、画像を適切に取得できるよう修正する。
```[tasklist]
### Tasks
- [ ] https://github.com/openameba/a11y-guidelines/issues/528
- [ ] https://github.com/openameba/a11y-guidelines/issues/529
- [ ] https://github.com/openameba/a11y-guidelines/issues/530
```

**Comment by tokimari** [comment]
https://github.com/openameba/a11y-guidelines/blob/master/npm_scripts/scrape.js#L32 このへんですね:eyes:

@sasaplus1 こちらどうでしょうか？？
最新PRでは正しく動いていそうです: https://github.com/openameba/a11y-guidelines/pull/402

**Comment by sasaplus1** [comment]
ちょっとタスクを具体的にしました。

**Comment by tokimari** [comment]
Tasklistすごい 🎉

**Comment by sasaplus1** [comment]
Tasklistがsunsetするそうなのでsub-issue化しました
