### ISSUE TITLE
各項目の参考リンクにWCAG2.1解説書を追加する

### ISSUE THREAD

**Issue by tokimari** [openameba/a11y-guidelines#64]
[WCAG2.1解説書](https://waic.jp/docs/WCAG21/)が公開されましたので、2.1で追加された項目に参考リンクを追加します。

### TODO
- [x] 1.3.4 Orientation （AA） - オリエンテーション
- [x] 1.3.5 Identify Input Purpose （AA） - 入力目的の特定
- 1.3.6 Identify Purpose （AAA） - 目的の特定: **本ガイドラインに記載無し**
- [x] 1.4.10 Reflow （AA） - リフロー
- 1.4.11 Non-Text Contrast （AA） - 非テキストコントラスト: **本ガイドラインに記載無し**
- 1.4.12 Text Spacing （AA） - テキストの間隔（行間や段落の間隔、文字間隔）: **本ガイドラインに記載無し**
- [x] 1.4.13 Content on Hover or Focus （AA） - ホバーまたはフォーカスで変化するコンテンツ
- [x] 2.1.4 Character Key Shortcuts （A） - 文字キーのショートカット
- 2.2.6 Timeouts （AAA） - タイムアウト: **本ガイドラインに記載無し**
- [x] 2.3.3 Animation from Interactions （AAA） - インタラクションからのアニメーション: https://github.com/openameba/a11y-guidelines/pull/239
- [x] 2.5.1 Pointer Gestures （A） - ポインタジェスチャ
- [x] 2.5.2 Pointer Cancellation （A） - ポインタキャンセル
- [x] 2.5.3 Label in Name （A） - 名前（name）のラベル
- [x] 2.5.4 Motion Actuation （A） - モーション（動作）による作動
- [x] 2.5.5 Target Size （AAA） - ターゲットのサイズ: **本ガイドラインでは現在公開無し（ https://github.com/openameba/a11y-guidelines/issues/14 ）**
- 2.5.6 Concurrent Input Mechanisms （AAA） - 多様な入力メカニズム: **本ガイドラインに記載無し**
- [x] 4.1.3 Status Messages （AA） - ステータスメッセージ
